"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-16 18:22:04.463817
"""

import sqlalchemy as sa
from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor", sa.String(length=128), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("entity", sa.String(length=64), nullable=False),
        sa.Column("entity_id", sa.String(length=64), nullable=False),
        sa.Column("before", sa.JSON(), nullable=True),
        sa.Column("after", sa.JSON(), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_log_at"), "audit_log", ["at"], unique=False)
    op.create_table(
        "conformal_offsets",
        sa.Column("bucket", sa.Integer(), nullable=False),
        sa.Column("window", sa.Integer(), nullable=False),
        sa.Column("level", sa.Float(), nullable=False),
        sa.Column("offset", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("bucket", "window", "level"),
    )
    op.create_table(
        "items",
        sa.Column("series_idx", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.String(length=40), nullable=False),
        sa.Column("store_id", sa.String(length=10), nullable=False),
        sa.Column("dept_id", sa.String(length=20), nullable=False),
        sa.Column("cat_id", sa.String(length=20), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("unit_cost", sa.Float(), nullable=False),
        sa.Column("lead_time", sa.Integer(), nullable=False),
        sa.Column("case_pack", sa.Integer(), nullable=False),
        sa.Column("moq", sa.Integer(), nullable=False),
        sa.Column("shelf_capacity", sa.Integer(), nullable=False),
        sa.Column("holding_cost_day", sa.Float(), nullable=False),
        sa.Column("shortage_cost", sa.Float(), nullable=False),
        sa.Column("velocity_bucket", sa.Integer(), nullable=False),
        sa.Column("on_hand", sa.Integer(), nullable=False),
        sa.Column("on_order", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("series_idx"),
    )
    op.create_index(op.f("ix_items_item_id"), "items", ["item_id"], unique=False)
    op.create_index(op.f("ix_items_store_id"), "items", ["store_id"], unique=False)
    op.create_table(
        "model_runs",
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_champion", sa.Boolean(), nullable=False),
        sa.Column("summary", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("run_id"),
    )
    op.create_table(
        "plans",
        sa.Column("plan_id", sa.String(length=36), nullable=False),
        sa.Column("store_id", sa.String(length=10), nullable=False),
        sa.Column("budget", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("scenario", sa.JSON(), nullable=False),
        sa.Column("created_by", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("decided_by", sa.String(length=128), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("total_units", sa.Integer(), nullable=False),
        sa.Column("total_cost", sa.Float(), nullable=False),
        sa.Column("lines_ordered", sa.Integer(), nullable=False),
        sa.Column("solver_status", sa.String(length=32), nullable=False),
        sa.Column("solve_seconds", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("plan_id"),
    )
    op.create_index(op.f("ix_plans_store_id"), "plans", ["store_id"], unique=False)
    op.create_table(
        "forecasts",
        sa.Column("series_idx", sa.Integer(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("p50", sa.Float(), nullable=False),
        sa.Column("model_version", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["series_idx"],
            ["items.series_idx"],
        ),
        sa.PrimaryKeyConstraint("series_idx", "day"),
    )
    op.create_table(
        "plan_lines",
        sa.Column("plan_id", sa.String(length=36), nullable=False),
        sa.Column("series_idx", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.String(length=40), nullable=False),
        sa.Column("target", sa.Float(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("need", sa.Float(), nullable=False),
        sa.Column("units", sa.Integer(), nullable=False),
        sa.Column("cost", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["plans.plan_id"],
        ),
        sa.ForeignKeyConstraint(
            ["series_idx"],
            ["items.series_idx"],
        ),
        sa.PrimaryKeyConstraint("plan_id", "series_idx"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("plan_lines")
    op.drop_table("forecasts")
    op.drop_index(op.f("ix_plans_store_id"), table_name="plans")
    op.drop_table("plans")
    op.drop_table("model_runs")
    op.drop_index(op.f("ix_items_store_id"), table_name="items")
    op.drop_index(op.f("ix_items_item_id"), table_name="items")
    op.drop_table("items")
    op.drop_table("conformal_offsets")
    op.drop_index(op.f("ix_audit_log_at"), table_name="audit_log")
    op.drop_table("audit_log")
    # ### end Alembic commands ###
